apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crashchart.fullname" . }}
  labels:
    {{- include "crashchart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "crashchart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "crashchart.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "crashchart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          # command: [ "/bin/bash", "-c", "--" ]
          # args: [ "while true; do sleep 30; done;" ]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: COMPlus_DbgEnableMiniDump
              value: "1"
            - name: COMPlus_DbgMiniDumpType
              value: "4"
            # COMPlus_DbgMiniDumpName is used to specify the runtime coredump name template. For now only "%d" is allowed.
            - name: COMPlus_DbgMiniDumpName
              value: "/cores/prober-core-%d"
          volumeMounts:
          - mountPath: /cores
            name: core-dump
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: core-dump
          hostPath:
            path: /Users/shivanshigupta/crashes